import type { Project } from '../src/types/content'

export const projects: Project[] = [
  {
    id:               'p1',
    title:            'Casa Serena',
    slug:             'casa-serena',
    location:         'Amalfi Coast, Italy',
    year:             2023,
    category:         'Residential',
    status:           'Completed',
    description:      'Perched on the rugged cliffs of the Amalfi Coast, Casa Serena is a meditation on the relationship between built form and natural landscape. Carved into the terraced hillside, the home unfolds in a series of horizontal planes that mirror the geometry of the surrounding terrain. Local travertine, hand-troweled plaster, and reclaimed olive wood root the structure in its Mediterranean context. Every room opens to the sea — a deliberate dissolution of boundaries between interior and exterior.',
    shortDescription: 'A cliffside residence that dissolves the boundary between architecture and landscape.',
    images: [
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600', alt: 'Casa Serena exterior', caption: 'Main facade facing the Tyrrhenian Sea' },
      { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600', alt: 'Living room interior', caption: 'Open-plan living with panoramic sea views' },
      { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600', alt: 'Pool terrace', caption: 'Infinity pool terrace at sunset' },
    ],
    featured: true,
    area:     '620 m²',
    client:   'Private',
    tags:     ['Travertine', 'Sea views', 'Terraced'],
  },
  {
    id:               'p2',
    title:            'Kōan Tower',
    slug:             'koan-tower',
    location:         'Tokyo, Japan',
    year:             2023,
    category:         'Commercial',
    status:           'Completed',
    description:      'Kōan Tower rises from the dense urban fabric of Minami-Aoyama as a vertical garden. The facade\'s rhythm of deep-set windows and planted terraces creates a shifting pattern of light and shadow throughout the day. At the ground level, a public atrium dissolves the typical barrier between street and lobby, drawing the city\'s energy inward. The structural logic, expressed honestly in exposed concrete, becomes the primary aesthetic statement.',
    shortDescription: 'A vertical garden tower that redefines the relationship between city and sky.',
    images: [
      { url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1600', alt: 'Kōan Tower exterior', caption: 'Street-level view, Minami-Aoyama' },
      { url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600', alt: 'Office interior', caption: 'Upper floor office space' },
    ],
    featured: true,
    area:     '12,400 m²',
    client:   'Aoyama Holdings',
    tags:     ['Concrete', 'Vertical garden', 'Public atrium'],
  },
  {
    id:               'p3',
    title:            'The Loom House',
    slug:             'loom-house',
    location:         'Hudson Valley, New York',
    year:             2022,
    category:         'Residential',
    status:           'Completed',
    description:      'The Loom House occupies a former textile mill site in the Hudson Valley, weaving together industrial heritage with contemporary domestic life. The original brick shell — preserved as a ruin fragment — frames a new glass and steel intervention that floats above the historic footprint. Inside, raw concrete meets hand-loomed textiles and the Hudson River becomes the perpetual backdrop.',
    shortDescription: 'Industrial heritage and contemporary living in dialogue above the Hudson River.',
    images: [
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600', alt: 'Loom House exterior', caption: 'Glass volume within the preserved brick shell' },
      { url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600', alt: 'Main living space', caption: 'Double-height living area' },
      { url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1600', alt: 'Kitchen detail', caption: 'Kitchen with reclaimed oak and concrete' },
    ],
    featured: true,
    area:     '480 m²',
    client:   'Private',
    tags:     ['Adaptive reuse', 'Industrial', 'Riverside'],
  },
  {
    id:               'p4',
    title:            'Pavilion du Lac',
    slug:             'pavilion-du-lac',
    location:         'Geneva, Switzerland',
    year:             2022,
    category:         'Cultural',
    status:           'Completed',
    description:      'Commissioned as a seasonal cultural pavilion on the shores of Lake Geneva, Pavilion du Lac explores the threshold between earth, water, and sky. The structure hovers above the water on slender steel columns, its mirrored underside reflecting the lake surface. At night, the pavilion becomes a lantern over the water.',
    shortDescription: 'A floating cultural pavilion that merges architecture with the landscape of Lake Geneva.',
    images: [
      { url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600', alt: 'Pavilion exterior', caption: 'View from the lakeside promenade' },
    ],
    featured: false,
    area:     '340 m²',
    client:   'City of Geneva',
    tags:     ['Lakeside', 'Steel', 'Cultural'],
  },
  {
    id:               'p5',
    title:            'Noir Residence',
    slug:             'noir-residence',
    location:         'Los Angeles, California',
    year:             2024,
    category:         'Residential',
    status:           'In Progress',
    description:      'Noir Residence is a study in restraint and contrast — a dark, monolithic form set against the bleached landscape of the Santa Monica Mountains. The all-black exterior absorbs heat and light, while the interior opens dramatically to a series of sky-lit courtyards. The material palette is deliberately narrow: black concrete, oiled steel, smoked oak, and aged bronze.',
    shortDescription: 'A monolithic dark form in dialogue with the bleached California landscape.',
    images: [
      { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600', alt: 'Noir Residence exterior', caption: 'West facade at dusk' },
      { url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600', alt: 'Courtyard', caption: 'Central sky-lit courtyard' },
    ],
    featured: false,
    area:     '720 m²',
    client:   'Private',
    tags:     ['Black concrete', 'Courtyard', 'Monolithic'],
  },
  {
    id:               'p6',
    title:            'Studio Luce',
    slug:             'studio-luce',
    location:         'Milan, Italy',
    year:             2021,
    category:         'Interior',
    status:           'Completed',
    description:      'Studio Luce is the flagship interior of a Milanese fashion house. A grid of bespoke alabaster light panels transforms the ceiling into a glowing surface, while curved plaster walls and polished terrazzo floors create a continuous, enveloping atmosphere. No artwork is needed; the architecture is the art.',
    shortDescription: 'A luminous flagship interior that transforms light itself into the primary material.',
    images: [
      { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1600', alt: 'Studio Luce main floor', caption: 'Main retail floor with alabaster ceiling panels' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1600', alt: 'Detail view', caption: 'Curved wall detail with bespoke lighting' },
    ],
    featured: false,
    area:     '280 m²',
    client:   'Confidential',
    tags:     ['Alabaster', 'Terrazzo', 'Retail'],
  },
]

export const getFeaturedProjects = (): Project[] =>
  projects.filter((p) => p.featured)

export const getProjectBySlug = (slug: string): Project | undefined =>
  projects.find((p) => p.slug === slug)
